import type { GovernanceChecklistSection } from "@/lib/types/governance";

/**
 * The canonical Beas Capital CG checklist — 51 items across 8 sections.
 *
 * Each item now carries the per-item metadata that cgchecklist2.0 encodes in its
 * `data/checklist.json` (`outputFormat` + green/red bands + a `sourceHint`).
 * This is the single source of truth the analysis engine iterates over: the
 * report is assembled by looping THESE items — never by parsing whatever the LLM
 * happened to return — so no question can silently go missing. The bands make
 * scoring rule-based (0 / 0.25 / 0.5) instead of a read on answer sentiment, and
 * `sourceHint` tells the engine where to answer each item from (financial
 * statements, harvested filings, exchange disclosures, or web research).
 */
export const GOVERNANCE_CHECKLIST: GovernanceChecklistSection[] = [
  {
    sectionId: "BOARD",
    title: "Board of directors",
    items: [
      {
        questionId: "BOARD-1",
        particulars: "Does the board consist of >50% independent directors?",
        outputFormat: "% independent",
        greenFlag: "≥50% independent; balanced board",
        redFlag: "<50% independent / only meets bare minimum",
        sourceHint: "annual_report",
      },
      {
        questionId: "BOARD-2",
        particulars: "Is chairman non-executive?",
        outputFormat: "Yes/No",
        greenFlag: "Non-executive chairman (ideally independent), separate from MD",
        redFlag: "Executive / promoter chairman, or chairman = MD",
        sourceHint: "annual_report",
      },
      {
        questionId: "BOARD-3",
        particulars:
          "All relationship or transaction of non-exec directors disclosed in AR?",
        outputFormat: "Yes/No",
        greenFlag: "All non-exec director relationships & transactions disclosed",
        redFlag: "Undisclosed relationships, ties or conflicts",
        sourceHint: "annual_report",
      },
      {
        questionId: "BOARD-4",
        particulars: "Disclosures to the remuneration paid",
        outputFormat: "Yes/No",
        greenFlag: "Director / KMP remuneration fully disclosed with figures",
        redFlag: "Remuneration not disclosed or opaque",
        sourceHint: "annual_report",
      },
      {
        questionId: "BOARD-5",
        particulars: "Reputation of the directors",
        outputFormat: "Text/Score",
        greenFlag: "Clean, well-regarded directors with credible records",
        redFlag: "Director(s) linked to past frauds, defaults or adverse records",
        sourceHint: "web",
      },
    ],
  },
  {
    sectionId: "AUDIT",
    title: "Audit",
    items: [
      {
        questionId: "AUDIT-1",
        particulars: "Auditors to the company - big 4?",
        outputFormat: "Categorical",
        greenFlag: "Big-4 / top-tier national firm",
        redFlag: "Small / obscure firm relative to company size",
        sourceHint: "annual_report",
      },
      {
        questionId: "AUDIT-2",
        particulars: "Subsidiary accounts audited by a big-4 auditor?",
        outputFormat: "Categorical",
        greenFlag: "Material subsidiaries audited by comparable-quality firms",
        redFlag: "Tiny / local auditors for material subsidiaries",
        sourceHint: "annual_report",
      },
      {
        questionId: "AUDIT-3",
        particulars: "Qualifications in the Auditor Report?",
        outputFormat: "Yes/No",
        greenFlag: "Clean, unqualified opinion",
        redFlag: "Qualified / going-concern / emphasis of matter",
        sourceHint: "annual_report",
      },
      {
        questionId: "AUDIT-4",
        particulars: "Remuneration paid to the auditors",
        outputFormat: "Text",
        greenFlag:
          "Auditor remuneration reasonable & in line with size / peers / revenue growth",
        redFlag:
          "Abnormally high vs revenue/EBIT or peers, or unusually low (scope concern)",
        sourceHint: "annual_report",
      },
      {
        questionId: "AUDIT-5",
        particulars: "Last change in auditors, reason for change",
        outputFormat: "Text",
        greenFlag: "No mid-term change / orderly rotation with clear reason",
        redFlag: "Resignation citing disagreement or info-access, or opaque change",
        sourceHint: "annual_report",
      },
    ],
  },
  {
    sectionId: "STAKEHOLDERS",
    title: "Stakeholders",
    items: [
      {
        questionId: "STAKEHOLDERS-1",
        particulars: "Free float in the market - high / low",
        outputFormat: "% free float",
        greenFlag: "High free float (≥35–40%)",
        redFlag: "Low free float (<15–25%, near MPS floor)",
        sourceHint: "financials",
      },
      {
        questionId: "STAKEHOLDERS-2",
        particulars: "Recent entry and exit by PE Funds/ HNIs",
        outputFormat: "Text",
        greenFlag: "Reputed investors entering / holding",
        redFlag: "Quality PE / HNI holders exiting",
        sourceHint: "web",
      },
    ],
  },
  {
    sectionId: "EMPLOYEE",
    title: "Employee",
    items: [
      {
        questionId: "EMPLOYEE-1",
        particulars: "Employee attrition",
        outputFormat: "%",
        greenFlag: "Attrition at or below industry",
        redFlag: "Attrition well above industry / rising",
        sourceHint: "annual_report",
      },
      {
        questionId: "EMPLOYEE-2",
        particulars: "Remuneration compared to industry standards",
        outputFormat: "Text",
        greenFlag: "Competitive vs industry",
        redFlag: "Well below (flight risk) or excessive vs industry",
        sourceHint: "web",
      },
      {
        questionId: "EMPLOYEE-3",
        particulars: "ESOP Pool",
        outputFormat: "%",
        greenFlag: "Reasonable broad-based ESOP pool, sensibly priced",
        redFlag: "None, or heavy / deep-discount / promoter-concentrated",
        sourceHint: "annual_report",
      },
    ],
  },
  {
    sectionId: "INDUSTRY_PROMOTER",
    title: "Industry and Promoter",
    items: [
      {
        questionId: "INDUSTRY_PROMOTER-1",
        particulars: "Promoter stake (%) (above 50 or below)",
        outputFormat: "%",
        greenFlag: "Promoter holding >50% (strong skin in the game)",
        redFlag: "Very low / sharply declining (<26%)",
        sourceHint: "financials",
      },
      {
        questionId: "INDUSTRY_PROMOTER-2",
        particulars: "Promoter stake trend over the last 8 quarters",
        outputFormat: "% + trend",
        greenFlag: "Stable or rising promoter holding",
        redFlag: "Steady decline or sharp drops",
        sourceHint: "financials",
      },
      {
        questionId: "INDUSTRY_PROMOTER-3",
        particulars: "Does the promoter have other material businesses ?",
        outputFormat: "Text",
        greenFlag: "Focused; no competing promoter businesses",
        redFlag: "Many competing / private promoter ventures",
        sourceHint: "web",
      },
      {
        questionId: "INDUSTRY_PROMOTER-4",
        particulars: "Is the business run by a professional CEO?",
        outputFormat: "Categorical",
        greenFlag: "Capable professional CEO, or strong engaged promoter with a bench",
        redFlag: "Weak promoter-dependence, no bench / key-person risk",
        sourceHint: "annual_report",
      },
      {
        questionId: "INDUSTRY_PROMOTER-5",
        particulars: "View on CEO",
        outputFormat: "Text/Score",
        greenFlag: "Strong capital-allocation & credibility track record",
        redFlag: "Poor capital allocation / credibility issues",
        sourceHint: "web",
      },
      {
        questionId: "INDUSTRY_PROMOTER-6",
        particulars: "Promoter vintage and involvment in business",
        outputFormat: "Text",
        greenFlag: "Long, engaged promoter vintage",
        redFlag: "Absentee or serial promoter",
        sourceHint: "annual_report",
      },
      {
        questionId: "INDUSTRY_PROMOTER-7",
        particulars: "Vintage of the top mgmt. team in the company",
        outputFormat: "Years",
        greenFlag: "Long-tenured, stable top team",
        redFlag: "High churn / recent senior exits",
        sourceHint: "annual_report",
      },
      {
        questionId: "INDUSTRY_PROMOTER-8",
        particulars: "Quality of second level team",
        outputFormat: "Text",
        greenFlag: "Deep, named second-level bench",
        redFlag: "Thin bench / key-person risk",
        sourceHint: "annual_report",
      },
      {
        questionId: "INDUSTRY_PROMOTER-9",
        particulars: "Family Dynamics - is there any fight?",
        outputFormat: "Yes/No",
        greenFlag: "No family disputes; clear succession (or not a family business)",
        redFlag: "Public family feud / succession dispute",
        sourceHint: "web",
      },
      {
        questionId: "INDUSTRY_PROMOTER-10",
        particulars: "Dealing with the government?",
        outputFormat: "Text",
        greenFlag: "Limited / transparent government dealings",
        redFlag: "Heavy discretionary government reliance",
        sourceHint: "web",
      },
      {
        questionId: "INDUSTRY_PROMOTER-11",
        particulars: "Cases from ED, SEBI, other institutions",
        outputFormat: "Count/Yes-No",
        greenFlag: "No SEBI / ED / CBI / SFIO cases or consent orders",
        redFlag: "Active or serious regulatory action / investigation",
        sourceHint: "web",
      },
      {
        questionId: "INDUSTRY_PROMOTER-12",
        particulars: "Political connect",
        outputFormat: "Text",
        greenFlag: "No / neutral political connection",
        redFlag: "Heavy political dependence",
        sourceHint: "web",
      },
      {
        questionId: "INDUSTRY_PROMOTER-13",
        particulars: "Transparency on analyst calls",
        outputFormat: "Yes/No",
        greenFlag: "Transparent, substantive analyst calls & disclosure",
        redFlag: "Opaque / evasive / no analyst calls",
        sourceHint: "annual_report",
      },
      {
        questionId: "INDUSTRY_PROMOTER-14",
        particulars: "Shareholding pledge?",
        outputFormat: "%",
        greenFlag: "Nil pledge (or <10%)",
        redFlag: "Pledge >25% or rising",
        sourceHint: "exchange",
      },
      {
        questionId: "INDUSTRY_PROMOTER-15",
        particulars: "Leverage",
        outputFormat: "D/E ratio",
        greenFlag: "Low leverage (D/E < 0.5–1.0) / net cash",
        redFlag: "High leverage (D/E > 2 / rising)",
        sourceHint: "financials",
      },
    ],
  },
  {
    sectionId: "STOCK_EXCHANGE",
    title: "Stock Exchange",
    items: [
      {
        questionId: "STOCK_EXCHANGE-1",
        particulars: "Adequate disclosures and compliance to SEBI Guidelines",
        outputFormat: "Yes/No",
        greenFlag: "Timely, compliant disclosures; no fines",
        redFlag: "Repeated delays / Reg 30 fines / non-compliance",
        sourceHint: "exchange",
      },
      {
        questionId: "STOCK_EXCHANGE-2",
        particulars: "Volatility in the stock",
        outputFormat: "Text",
        greenFlag: "Volatility in line with the market",
        redFlag: "Abnormal / operator-like moves",
        sourceHint: "web",
      },
      {
        questionId: "STOCK_EXCHANGE-3",
        particulars: "Volume and liquidity in the stock - high / low?",
        outputFormat: "Text",
        greenFlag: "Adequate daily volume & liquidity",
        redFlag: "Very thin / illiquid",
        sourceHint: "web",
      },
      {
        questionId: "STOCK_EXCHANGE-4",
        particulars: "Covered by domestic / mnc coverage",
        outputFormat: "Count",
        greenFlag: "Covered by multiple reputed research houses",
        redFlag: "No / captive coverage",
        sourceHint: "web",
      },
    ],
  },
  {
    sectionId: "OTHER_REGULATORY",
    title: "Other Regulatory",
    items: [
      {
        questionId: "OTHER_REGULATORY-1",
        particulars: "Contingent tax or liability - if material",
        outputFormat: "₹ / % net worth",
        greenFlag: "Contingent tax/liability small & immaterial vs net worth",
        redFlag: "Large / material vs net worth, rising or adverse-probable",
        sourceHint: "annual_report",
      },
    ],
  },
  {
    sectionId: "FINANCIALS",
    title: "Financials",
    items: [
      {
        questionId: "FINANCIALS-1",
        particulars:
          "Material red flags in notes to accounts and contingent liabilities",
        outputFormat: "Text",
        greenFlag: "No material red flags in notes / contingent liabilities",
        redFlag:
          "Material red flags (fraud, large CLs, aggressive accounting)",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-2",
        particulars: "Debt & Advances - high / low?",
        outputFormat: "Text",
        greenFlag: "Modest debt & advances",
        redFlag: "High debt and/or large advances out",
        sourceHint: "financials",
      },
      {
        questionId: "FINANCIALS-3",
        particulars: "Receivables > 6 months as a % of revenues",
        outputFormat: "% of receivables / revenue",
        greenFlag: "Aged receivables (>6m) low (<5–10%), flat or declining",
        redFlag: ">20–25%, or steadily rising and high vs peers",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-4",
        particulars: "Bankers? Top pvt/psu or not?",
        outputFormat: "Categorical",
        greenFlag: "Top private / PSU / MNC bankers",
        redFlag: "Only marginal / obscure lenders",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-5",
        particulars: "Consistent Dividend payout",
        outputFormat: "Yes/No",
        greenFlag: "Consistent payout supported by profits & cash",
        redFlag: "Erratic / nil, or paid despite losses / weak cash flow",
        sourceHint: "financials",
      },
      {
        questionId: "FINANCIALS-6",
        particulars: "Cash EPS vs Accounting EPS - Low or high",
        outputFormat: "Ratio",
        greenFlag: "Cash EPS close to or above accounting EPS",
        redFlag: "Cash EPS materially below accounting EPS",
        sourceHint: "financials",
      },
      {
        questionId: "FINANCIALS-7",
        particulars: "Disclosure on all related party transaction",
        outputFormat: "Yes/No",
        greenFlag: "All RPTs disclosed and independently arm's-length",
        redFlag: "Undisclosed or large promoter-routed RPTs",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-8",
        particulars: "CFO / EBITDA",
        outputFormat: "Ratio",
        greenFlag: "CFO/EBITDA ≥ 0.6–0.7 (good cash conversion)",
        redFlag: "CFO/EBITDA < 0.4 (weak conversion)",
        sourceHint: "financials",
      },
      {
        questionId: "FINANCIALS-9",
        particulars: "Provisioning",
        outputFormat: "Text",
        greenFlag: "Conservative, adequate provisioning",
        redFlag: "Under-provisioned or suspicious write-backs",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-10",
        particulars: "Fluctuating depreciation rates",
        outputFormat: "Text",
        greenFlag: "Stable depreciation rates / policy",
        redFlag: "Declining rates or extended useful lives (profit-boosting)",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-11",
        particulars: "Other noteable red flags",
        outputFormat: "Text",
        greenFlag: "No other notable red flags",
        redFlag: "Other governance / forensic red flags present",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-12",
        particulars: "Working capital cycle",
        outputFormat: "Trend (days)",
        greenFlag: "Stable or improving working-capital cycle",
        redFlag: "Working capital rising faster than sales",
        sourceHint: "financials",
      },
      {
        questionId: "FINANCIALS-13",
        particulars: "Are auditor fees transparently disclosed?",
        outputFormat: "Yes/No",
        greenFlag: "Auditor fees transparently disclosed with breakup",
        redFlag: "Fees opaque or not broken out",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-14",
        particulars: "Is asset growth significantly outpacing revenue growth?",
        outputFormat: "Text",
        greenFlag: "Asset growth broadly in line with revenue",
        redFlag: "Asset growth significantly outpacing revenue",
        sourceHint: "financials",
      },
      {
        questionId: "FINANCIALS-15",
        particulars: "Are contingent liabilities greater than 20x net worth?",
        outputFormat: "% net worth (20x test)",
        greenFlag: "Contingent liabilities well below 20x net worth",
        redFlag: "Contingent liabilities greater than 20x net worth",
        sourceHint: "annual_report",
      },
      {
        questionId: "FINANCIALS-16",
        particulars: "Is provisioning coverage below industry norms or falling?",
        outputFormat: "Text",
        greenFlag: "Provisioning coverage adequate and stable",
        redFlag: "Provisioning coverage below industry norms or falling",
        sourceHint: "annual_report",
      },
    ],
  },
];

export const GOVERNANCE_TOTAL_ITEMS = GOVERNANCE_CHECKLIST.reduce(
  (sum, section) => sum + section.items.length,
  0,
);

export const GOVERNANCE_TOTAL_MAX_SCORE = GOVERNANCE_TOTAL_ITEMS * 2;
