import { getCloudflareContext } from "@opennextjs/cloudflare";
import type { CompanyCacheRecord, VerificationRecord } from "./types";

// Run records expire a day after creation — long enough for a routine run to
// land, short enough not to accumulate.
const RECORD_TTL_SECONDS = 60 * 60 * 24;

// Final per-company output is cached for 15 days.
const COMPANY_TTL_SECONDS = 60 * 60 * 24 * 15;

const keyFor = (runId: string) => `run:${runId}`;

// Cache is keyed by ticker alone — anyone who runs that ticker within the
// window gets the stored copy, regardless of how country was (or wasn't) set.
const companyKey = (ticker: string) => `company:${ticker.toUpperCase()}`;

// Minimal KV surface we use, declared locally so this module compiles without
// the gitignored `cloudflare-env.d.ts` (generated by `npm run cf-typegen`).
interface VerifyKv {
  get(key: string): Promise<string | null>;
  put(
    key: string,
    value: string,
    options?: { expirationTtl?: number },
  ): Promise<void>;
}

const getKv = async (): Promise<VerifyKv> => {
  const { env } = await getCloudflareContext({ async: true });
  const kv = (env as unknown as Record<string, unknown>).VERIFY_KV as
    | VerifyKv
    | undefined;
  if (!kv) {
    throw new Error(
      "VERIFY_KV namespace is not bound. Create it with `wrangler kv namespace create VERIFY_KV` and set its id in wrangler.jsonc.",
    );
  }
  return kv;
};

export const putRecord = async (record: VerificationRecord): Promise<void> => {
  const kv = await getKv();
  await kv.put(keyFor(record.runId), JSON.stringify(record), {
    expirationTtl: RECORD_TTL_SECONDS,
  });
};

export const getRecord = async (
  runId: string,
): Promise<VerificationRecord | null> => {
  const kv = await getKv();
  const raw = await kv.get(keyFor(runId));
  if (!raw) return null;
  try {
    return JSON.parse(raw) as VerificationRecord;
  } catch {
    return null;
  }
};

export const putCompanyCache = async (
  record: CompanyCacheRecord,
): Promise<void> => {
  const kv = await getKv();
  await kv.put(companyKey(record.ticker), JSON.stringify(record), {
    expirationTtl: COMPANY_TTL_SECONDS,
  });
};

export const getCompanyCache = async (
  ticker: string,
): Promise<CompanyCacheRecord | null> => {
  const kv = await getKv();
  // KV auto-expires the key at 15 days, so its presence means it's still fresh.
  const raw = await kv.get(companyKey(ticker));
  if (!raw) return null;
  try {
    return JSON.parse(raw) as CompanyCacheRecord;
  } catch {
    return null;
  }
};
